### PR TITLE
PR for week 2

### PR DESCRIPTION
**Pull request by shuyuhuang23**
http://13.230.113.132:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Layout exceeds screen width in small to middle size devices.
2. Content in header, keyvisual and attraction list should align with each other to left or right in any devices larger than 1200px.
3. Layout of category names is incorrect obviousely.
4. Your code will load the same page multiple times if we scroll down and up quickly. Try testing live URL, not just in your local machine.

**Comment by shuyuhuang23** [comment]
老師，針對這些回饋，想進一步確認：

   1. Layout exceeds screen width in small to middle size devices.
   想問一下，當螢幕尺寸介於 360 & 1200 中間時，畫面應該要長什麼樣子？比如景點一排四個，要變成一排兩個？
   2. Content in header, keyvisual and attraction list should align with
   each other to left or right in any devices larger than 1200px.
   figma attraction list (attractions group) 的寬度為 1170，header 為
   1200，所以本來就不會完全靠左切齊？
   3. Layout of category names is incorrect obviousely.
   不太確定這一點的意思，可以請老師再說明一下嗎？
   4. Your code will load the same page multiple times if we scroll down
   and up quickly. Try testing live URL, not just in your local machine.
   我測試過就算上下快速滑動，也不會重複 call 一樣的 api。可否請老師再給點提示？

[image: image.png]

以上疑問，再麻煩老師回覆，感謝。

Shuyu Huang


Chao-Wei Peng ***@***.***> 於 2022年11月27日 週日 晚上9:46寫道：

**Comment by cwpeng** [comment]
1. Your idea is OK.
2. Yes, but almost align to left. Your text in keyvisuals are far away.
3. Category names arrange in 3 columns. Yours only 1 column.
4. Try testing in live URL, not just in your local machine.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Many issues are still there.
未命名-2

**Comment by shuyuhuang23** [comment]
I have added isLoading variable to avoid loading repeatedly and also successfully tested in live URL. I cannot reproduce the issue even if i checked on the "disable cache" option. Can you please check the code for me?

**Review by cwpeng — CHANGES_REQUESTED** [review]
Final layout issue: content in header, keyvisual and attraction list should align with each other to left or right in any devices larger than 1200px.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout issue: content in header, keyvisual and attraction list should align with each other to left or right in any devices larger than 1200px.

You can contact me in Discord if you don't get what I say.

**Review by cwpeng — APPROVED** [review]
Good. Done. Keep Going.

**Pull request merged**
